### ISSUE TITLE
Original repo active again?

### ISSUE THREAD

**Issue by jacobwhall** [jacobwhall/marktext#18]
The original maintainer of MarkText [appears to be active again](https://github.com/marktext/marktext/issues/3597#issuecomment-1663995077). While we've made some progress on this fork, I think that if the original repo becomes active again it would be wise to sunset this fork so that we don't split the community. That said, I'm going to give it some time and see how things go.

**Comment by jacobwhall** [comment]
The situation is unclear. This repository is still attracting interest (issues, stars), so I think I'll keep this fork alive for now.

**Comment by tejasraman** [comment]
> The situation is unclear. This repository is still attracting interest (issues, stars), so I think I'll keep this fork alive for now.

It might be nice to try and PR some of your fixes into MarkText.

**Comment by jacobwhall** [comment]
> It might be nice to try and PR some of your fixes into MarkText.

@tejasraman almost everything in this repository was merged in from an active PR on the upstream repository. See [the releases page](https://github.com/jacobwhall/marktext/releases) for more information!

**Comment by jacobwhall** [comment]
Since development seems to still be stalled / slow upstream, I'm closing this issue. I'll re-open it if the need arises.
